index.html
removed extra content like xyzstreet , phone number and social media links from the top of website , to ensure a better look and design of the website 
Before :
After :
=> fix: removed topbar 

README.md
Solves #4 
Added a Contributors Section to the current README.md
Please check it and let me know. Thanks
=> Added Contributors Section to Readme.md (Solves #4)

about.html, appointment.html, contact.html, css/style.css, feature.html, index.html, scss/bootstrap/scss/_dropdown.scss, service.html, team.html, testimonial.html
#10 
Before
After
I have upgraded all the slides nav bar If you liked the navbar then upgrade this to intermediate as
this issue is only for appointment but I have done best for the nav bar.
=> nav bar upgraded

about.html, appointment.html, contact.html, css/style.css, feature.html, index.html, scss/bootstrap/scss/_dropdown.scss, service.html, team.html, testimonial.html
Alignment in the team members card.
=> Adding Features Therapists Section

about.html
#22 
Added images in the therapists section
=> adding images in about section

css/bootstrap.min.css, service.html, testimonial.html
This PR addresses three specific design and content issues across the project to enhance consistency, improve visual appeal, and ensure accurate representation of information.
Changes Made
1. Heading Color Issue on Testimonial Page
2. Replace Lorem Ipsum Text
3. Add Photos in Pre-Trained Therapists Section
=> Content/Media Update

about.html, appointment.html, contact.html, css/style.css, feature.html, service.html, team.html, testimonial.html
#21 
Applying Hover Effect  On Social Media Icons present in TopBar
=> Hover Effect on Topbar Social Media Icons

appointment.html, contact.html, css/style.css, index.html, service.html, testimonial.html
Changing text color from white to black 
- text should be Visible
- Updating required attribute In Form Tag
#27
=> Text color - Testimonial, Services

css/style.css
- Enhanced the appearance of the scrollbar:
> - Updated the scrollbar style to make it more sleek and minimal.
> -  Applied a smooth transition effect when hovering over the scrollbar.
> - Changed the scrollbar's track background to a  subtle style for a cleaner look.
> - Ensuring the scrollbar blends well with the overall UI design while maintaining functionality.
- Before:
- After: 
- Changes in the Code:
> - Modified the css/style.css file to include new styles for the scrollbar.
> - Adjusted the scrollbar's ::-webkit-scrollbar elements (e.g., ::-webkit-scrollbar-track, ::-webkit-scrollbar-thumb).
=> Update the styles in the css/style.css file to improve scroll bar

index.html
Change the image because every image should match the others.
- Same Size
- Same Contract
- Same Opacity and much more
=> change-image-in-home-section

about.html, appointment.html, contact.html, css/bootstrap.min.css, feature.html, index.html, lib/wow/customcursor.css, lib/wow/customcursor.js, service.html, team.html, testimonial.html
custom cursor has been added and default cursor is being hidded.
https://github.com/user-attachments/assets/d825e498-bd73-47d4-861d-501dd94b4297
=> Default Cursor hided

about.html, appointment.html, contact.html, feature.html, index.html, lib/wow/customcursor.css, lib/wow/customcursor.js, service.html, team.html, testimonial.html
Here in the video, we can see that cursor effect has been added.
Pls assign the label of SWOC25 and merge it under "intermediate" or "advance"
https://github.com/user-attachments/assets/c7b3b606-e15a-4cd5-8b02-e7f2f54d626d
=> custom cursor added

about.html, appointment.html, contact.html, feature.html, index.html, lib/wow/customcursor.css, lib/wow/customcursor.js, service.html, team.html, testimonial.html
The chatbot has been integrated.
Pls merge it asap under SWOC25
https://github.com/user-attachments/assets/09caedc9-e552-4803-92ec-a707559c8d89
=> Chatbot has been integrated

about.html, feature.html, service.html, testimonial.html
There was a bug where the images were not displayed in the testimonial section's image slider.
=> Adding images on slider - Testimonial Section

about.html, feature.html, service.html
#40  
Page name was written wrong in some files like about, feature, and service HTML
=> Update in text - Testimonial

css/style.css
**fixed issue no: #50**
🎉 **Achievement Unlocked!** I successfully resolved the overlapping issue between the chatbot and the scroll-to-top button on the webpage. 🛠️ Here's what I did:  
1️⃣ **Analyzed the Problem**:  
The chatbot and the scroll button were overlapping due to their conflicting positions in the layout. This impacted the user experience and made it difficult to access either element smoothly.  
2️⃣ **Implemented Adjustments**:  
- Tweaked the `right` and `bottom` positioning of the scroll button to avoid any clashes with the chatbot.  
- Verified responsiveness to ensure the changes work across different screen sizes.  
3️⃣ **Thorough Testing**:  
- Tested the changes on multiple devices and screen resolutions to ensure the issue was resolved across all scenarios.  
- …
=> 🚀 Fixed Overlapping Issue Between Chatbot and Scroll Button 🎯

css/bootstrap.min.css, index.html
Description
text in dark mode had poor visibility due to low contrast. The previous text color was too light, making it difficult to read on dark backgrounds. 
The updated color ensures better readability in both light and dark modes while maintaining accessibility standards.
Issue :
Fix text color visibility in Dark Mode #49 
Changes Implemented:
Adjusted the text color to improve contrast in dark mode.
Ensured readability in both light and dark themes.
Verified compliance with accessibility contrast guidelines. 
Screenshots:
After changing
Testing & Validation:
Tested in both light and dark themes.
Checked contrast ratios to meet accessibility standards.
No breaking changes; UI remains consistent.
=> Fixed color visibility in dark mode

about.html, feature.html
There are image tags used in the program for unavailable images. 
Due to which page not looks good
I've removed that.
Issue: #51 
@ThunderShadows Please review my PR.
=> Removed the unavailable images

index.html
**fixed issue no: #53**
I have successfully **fixed the scroll button icon** on the homepage, ensuring a **seamless and visually appealing user experience**. 🔥  
🔹 **Before Fixing:** The scroll button had an improper or missing icon, which affected its usability and design consistency.  
🔹 **What I Did:**  
✅ Updated the **icon styling** and ensured it aligns perfectly with the UI.  
✅ Used **Font Awesome** to enhance the button's appearance with a proper **arrow-up** icon.  
✅ Improved **button visibility** by making sure it appears smoothly when scrolling down and disappears when at the top.  
✅ Added **hover effects** for a better interactive experience.  
✅ Ensured the **responsive behavior** works perfectly across different screen sizes.  
🔹 **After Fixing:** Now, the scroll button …
=> 🚀 Fixed the Scroll Button Icon for a Better UI Experience! 🎯

about.html, appointment.html, contact.html, css/style.css, feature.html, index.html, service.html, team.html, testimonial.html
#57 adding payment options in footer
@ThunderShadows 
I added payment options in footer in required files like 
1. about.html
2. appointment.html
3. contact.html
4. features.html
5. index.html
6. service.html
7. team.html
8. testimonials.html
9. styles.css 
- I hope there will be no conflicts. Please inform me if any changes are required and merge it.
result seems like 
Thank You
=> adding payment options in footer #57

about.html, appointment.html, contact.html, feature.html, index.html, service.html, team.html
in your website i update twitter logo through out every page of every section of every card.  #71
=> Twitter logo update with new one in every page

about.html
**fixed issue #62**
**🔧 Description:**  
I have successfully **fixed the scroll button icon** on the **About Page**! 🎯 Previously, the icon had some misalignment issues, which affected the **user experience and overall aesthetics** of the page. After careful debugging and adjustments, I have:  
✅ **Replaced the old icon** with a more visually appealing one 🎨  
✅ **Ensured proper alignment** so that it doesn’t overlap with other elements 📏  
✅ **Maintained responsiveness** across different screen sizes 📱💻  
✅ **Tested functionality** to ensure smooth scrolling 🚀  
Now, users can **seamlessly navigate** back to the top of the page with an improved, more intuitive, and **aesthetically pleasing scroll button**! 🏆✨  
**preview**
---
---
=> 🚀 Fixed Scroll Button Icon on About Page 🛠️

about.html, contact.html, contributors.html, css/contributors.css, feature.html, index.html, js/contributors.js, service.html, team.html, testimonial.html
issue #64 
I have added contributor page in the website.
I have also created certificates for contributors so that contributors can download their certificates.
https://github.com/user-attachments/assets/77d852c9-21bb-41d9-91a0-92603746b301
=> Added cotributor page

index.html
- Previously, the home page had bright neon color in dark mode which was not uniform across different pages of the website and was also not matching the aesthetics of the website:
- Now, changes have been made in the CSS of the index.html file by changing the text color to white and keeping it uniform across multiple pages
=> Adjust the text color in dark mode for clear visibility

index.html
- I have set the default text color to black #000000 so that the text color remains consistent
-  Previously, the text color was bluish and was not consistent with different pages
- Now , I have adjusted the text color to remain consistent with the rest of the pages
- This Pull Request solves issue #78
=> Updated default text color and transition time

appointment.html, index.html, service.html
- Corrected the input types
- Adjusted patterns of the forms so that users give correct input format
- Removed redundant placeholders and corrected pattern mistakes for the forms inside index.html, appointment.html and service.html
- Changes made ensure correct input is given by users:
- This Pull Request resolves issue #90
=> Updated patterns, placeholders and input types of forms

index.html
- Previously, the hamburger menu was not visible in the index.html (home page)
- This was not contributing to the responsive design of the website
- Now, necessary changes have been made in the index.html file
- Hamburger menu is now visible in the index.html (home) page of the website at smaller screen resolutions adding to the responsiveness of the overall website
- This Pull Request resolves issue #103
=> Added hamburger menu to improve responsiveness
